name: Java CI with Gradle

on:
  push:
    branches: [ main, 'release/**', main, 'feature/**'  ]
  pull_request:
    branches: [ main, 'release/**', main, 'feature/**'  ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
          cache: 'gradle'
      - name: Run e2e tests
        run: ./gradlew :wgpu4k-e2e:e2eTest --stacktrace --info

