name: Java CI with Gradle

on:
  push:
    branches: [ main, 'release/**', main, 'feature/**'  ]
  pull_request:
    branches: [ main, 'release/**', main, 'feature/**'  ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: debug
        run: npx envinfo --preset playwright

